## login to Cloudservices and receive authentication Token
- name: send login to F5 Cloud Services API and receive authentication token
  uri:
    url: "https://api.cloudservices.f5.com/v1/svc-auth/login"
    method: POST
    headers:
      Content-Type: "application/json"
    body:
      username: "{{f5cs_username}}"
      password: "{{f5cs_password}}"
    body_format: json
  register: auth_response

- name: set auth token in variable
  set_fact:
    f5_auth_token: "{{auth_response.json.access_token}}"
  when: auth_response is success

#- name: show auth token
#  debug:
#    msg: "{{ f5_auth_token }}"

## Collect required account information
- name: receive Account information
  uri:
    url: "https://api.cloudservices.f5.com/v1/svc-account/user"
    method: GET
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ f5_auth_token }}"
      Content-Type: "application/json"
  register: user_details

#- name: show user details
#  debug:
#    msg: "{{ user_details }}"

- name: set primary account ID in variable
  set_fact:
    user_account_id: "{{user_details.json.primary_account_id}}"
  when: user_details is success
