---

  - name: Create letsencrypt directory in playbook directory
    ansible.builtin.file:
      path: '{{ letsencrypt_dir }}'
      state: directory

  - name: "Create required sub directories in playbook/letsencrypt directory"
    file:
      path: '{{ letsencrypt_dir }}/{{ item }}'
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx
    with_items:
    - account
    - certs
    - csrs
    - keys

## Create new Letsencrypt account key if flag is set

  - name: "Generate a Let's Encrypt account key"
    shell: "openssl genrsa 4096 | sudo tee {{ letsencrypt_account_key }}"
    when: new_le_account_key | bool

## Create a Letsencrypt account key if it does not exist
  - name: "Generate a Let's Encrypt account key"
    shell: "if [ ! -f {{ letsencrypt_account_key }} ]; then openssl genrsa 4096 | sudo tee {{ letsencrypt_account_key }}; fi"
    when: not new_le_account_key
